services:

    mirsch.admin.event_listener.locale_listener:
        class: Mirsch\Bundle\AdminBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    mirsch.admin.event_listener.user_locale_listener:
        class: Mirsch\Bundle\AdminBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
